### ISSUE TITLE
The virtual environment should be removed

### ISSUE THREAD

**Issue by patrickmcnamara** [paulfsheridan/ploomberg-terminal#1]
It is probably a bad idea to include the Python virtual environment in the git repo as each virtual environment is *mostly* specific to the machine that it is created on.

For example, a lot of the files in the virtual environment are symbolic links with hard-coded full paths to files on your computer, @paulfsheridan.

It's best to allow users to create virtual environments themselves as necessary.

**Comment by paulfsheridan** [comment]
Thanks, I have removed the virtual environment and added a requirements.txt so users can activate their own virtualenv and pip install the requirements.
